version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - files/*
    - appspec.yml
cache:
  paths:
    - '/root/.m2/**/*'