version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Docker
      - yum update -y
      - yum install -y docker
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 963894786913.dkr.ecr.us-east-1.amazonaws.com/transit-delay-service
  build:
    commands:
      - echo Build started on `date`
      - mvn test
      - mvn package
      - echo Building Docker image
      - docker build -t transit-delay-service .
      - docker tag transit-delay-service:latest 963894786913.dkr.ecr.us-east-1.amazonaws.com/transit-delay-service
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to ECR
      - docker push 963894786913.dkr.ecr.us-east-1.amazonaws.com/transit-delay-service:latest